### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Rhinowiwina**

### CODE REVIEW

**Review by SaintPatricksCoin — APPROVED** [review]
[https://wishoo.ecoinofficial.org/r/12cfip](Join Ecoins!)

**Review by jay12716 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Good

**Review by ghost — CHANGES_REQUESTED** [review]
Yes

**Comment by Genio40921** [comment]
gh pr checkout 55

**Pull request closed without merging**
